import "server-only";

export const dimensions = [
  { key: "issuePosition", label: "Issue & Position" },
  { key: "evidenceInformation", label: "Evidence & Information" },
  { key: "exposureStakes", label: "Exposure & Stakes" },
  { key: "actionsEscalation", label: "Actions & Escalation" },
  { key: "optionsAwareness", label: "Options Awareness" },
  { key: "preparedness", label: "Preparedness" },
] as const;

export const dimensionIntroductions = {
  issuePosition: {
    heading: "Separate the dispute from the story around it",
    body: "Disputes become harder to assess when the original issue, later events, assumptions and positions taken begin to merge. Cosil starts by separating those layers. This section tests whether the dispute itself is sufficiently clear before anything is decided about it."
  },
  evidenceInformation: {
    heading: "Test what the information actually establishes",
    body: "Having a large file is not the same as having a clear evidential picture. Cosil looks at whether the available material tells a coherent story, what rests on record rather than recollection, and where uncertainty remains. This section tests the strength of that picture without assessing the merits of your case."
  },
  exposureStakes: {
    heading: "Look beyond the headline issue",
    body: "The amount, complaint or event at the centre of a dispute may be only one part of the exposure. Time, relationships, future dealings, governance, reputation and the consequences of delay can matter too. This section tests how widely you are currently seeing what is at stake."
  },
  actionsEscalation: {
    heading: "Identify what has changed the dispute",
    body: "Not every email, meeting or event carries equal weight. Some actions change tone, narrow positions, introduce formality or become turning points. Cosil examines the dispute as a developing sequence, not simply a chronology. This section tests how clearly you can see that progression."
  },
  optionsAwareness: {
    heading: "See the decision landscape, not just the obvious route",
    body: "A dispute can feel as though it has only one next step, particularly once positions harden. Cosil tests whether the available landscape is understood before strategy is considered. This section examines your awareness of the different ways a matter may be managed, without selecting a route for you."
  },
  preparedness: {
    heading: "Move from reaction to a decision-ready view",
    body: "Being immersed in a dispute can make the latest development feel like the whole problem. Readiness requires enough distance to distinguish what is established, what remains uncertain and what factors genuinely matter to the next decision. This section tests whether you can currently see the matter at that level."
  },
} as const;

export const questions = [
  { id:"q1_1", dimension:"issuePosition", prompt:"How clearly can you separate the issue that first brought the dispute to your attention from the matters that are now genuinely in disagreement?", options:[["I find it difficult to separate them clearly",0],["I can identify the main issue, but other points have become mixed into it",1],["I can distinguish the original issue from the points that are now genuinely disputed",2]] },
  { id:"q1_2", dimension:"issuePosition", prompt:"If the other party described this dispute without reference to your account, how clearly could you identify where their version would materially differ from yours?", options:[["I would struggle to identify the differences clearly",0],["I could identify some, but there are areas I am unsure about",1],["I could clearly identify the main points where our accounts or positions differ",2]] },
  { id:"q1_3", dimension:"issuePosition", prompt:"When considering your own position, how confidently can you distinguish between what you believe happened, what can presently be established, and what remains disputed or uncertain?", options:[["Those things are still quite difficult to separate",0],["I can distinguish some of them, but there are areas of uncertainty",1],["I can distinguish clearly between my understanding, what is presently established and what remains disputed",2]] },
  { id:"q1_4", dimension:"issuePosition", prompt:"If the outcome you are currently seeking were achieved tomorrow, how confident are you that it would resolve the underlying dispute rather than only the issue presently receiving the most attention?", options:[["I have not really considered that distinction",0],["I think it would help, but some issues might remain",1],["I have considered this and understand what would, and would not, be resolved",2]] },

  { id:"q2_1", dimension:"evidenceInformation", prompt:"When you think about the important events in this dispute, how confidently can you distinguish between what is supported by information available to you and what currently depends mainly on recollection or assumption?", options:[["I have not really separated those things",0],["I can distinguish some, but there are important areas where I am unsure",1],["I can clearly distinguish what is supported from what remains based on recollection or assumption",2]] },
  { id:"q2_2", dimension:"evidenceInformation", prompt:"If someone with no previous involvement reviewed the matter, how clearly could the information available to you show what happened, in what order, and when the significant points of disagreement emerged?", options:[["The sequence would be difficult to establish",0],["The main sequence is identifiable, but there are gaps or areas of uncertainty",1],["The significant events and development of the dispute can be followed clearly",2]] },
  { id:"q2_3", dimension:"evidenceInformation", prompt:"How confident are you that you can distinguish information that is central to the dispute from material that provides background but may not affect the main points in disagreement?", options:[["I have a lot of information but have not really made that distinction",0],["I can identify some of the important material, but not consistently",1],["I can distinguish the information central to the dispute from the wider background",2]] },
  { id:"q2_4", dimension:"evidenceInformation", prompt:"When the available information does not fully support your recollection or understanding of an event, how clearly do you recognise that difference?", options:[["I have not really tested my understanding in that way",0],["I recognise some differences, although there are areas I remain uncertain about",1],["I can identify where the available information supports, differs from, or does not resolve my understanding",2]] },

  { id:"q3_1", dimension:"exposureStakes", prompt:"Beyond the issue receiving the most attention, how clearly have you identified what could actually be affected if the dispute remains unresolved or escalates?", options:[["I am mainly focused on the immediate issue",0],["I have considered some wider consequences",1],["I have a clear view of the main financial, practical, commercial or relational consequences",2]] },
  { id:"q3_2", dimension:"exposureStakes", prompt:"If the dispute remained unresolved for another six months, how clearly could you identify which consequences would become more significant?", options:[["I have not really considered the effect of the dispute continuing",0],["I can identify some likely consequences, but not their wider significance",1],["I have considered how the consequences could change or increase over time",2]] },
  { id:"q3_3", dimension:"exposureStakes", prompt:"How carefully have you considered whether the outcome you are pursuing remains proportionate to the financial, practical, commercial or relational consequences of continuing the dispute?", options:[["I have mainly concentrated on achieving the outcome",0],["I have considered proportionality to some extent",1],["I have weighed the outcome against the wider consequences of pursuing it",2]] },
  { id:"q3_4", dimension:"exposureStakes", prompt:"If you could protect only one thing as this dispute develops, how clearly could you identify what matters most: the financial position, the underlying relationship, time, reputation, governance, operational stability, or something else?", options:[["I have not identified a clear priority",0],["I have some sense of what matters most, but competing concerns remain",1],["I can clearly identify the consequence or interest that matters most to me",2]] },

  { id:"q4_1", dimension:"actionsEscalation", prompt:"How clearly can you identify anything already communicated, agreed, rejected, delayed or left unanswered that may have changed the position since the dispute began?", options:[["I have not really considered the dispute in those terms",0],["I can identify some significant developments, but I am unsure about others",1],["I can clearly identify the significant developments that have shaped the current position",2]] },
  { id:"q4_2", dimension:"actionsEscalation", prompt:"How clearly do you understand where the matter currently sits between an informal disagreement and a more formal dispute or process?", options:[["I am not clear how far the matter has progressed",0],["I have a general sense, but some aspects are unclear",1],["I understand how the matter has developed and its current stage",2]] },
  { id:"q4_3", dimension:"actionsEscalation", prompt:"Looking at the communications and actions on both sides, how clearly can you recognise whether positions have become more fixed as the dispute has developed?", options:[["I have not really considered how the positions have changed",0],["I can see some signs of positions becoming more defined or difficult",1],["I have a clear understanding of how both positions have developed over time",2]] },
  { id:"q4_4", dimension:"actionsEscalation", prompt:"Have you considered whether anything already done, communicated or allowed to progress may now be difficult to reverse?", options:[["I have not considered this",0],["I have considered it to some extent, but I am uncertain about the significance",1],["Yes, I have considered which developments may now be difficult to reverse",2]] },

  { id:"q5_1", dimension:"optionsAwareness", prompt:"When you think about how this dispute might be dealt with, how clearly can you distinguish between the different routes potentially open to you rather than focusing mainly on one?", options:[["I am mainly focused on one route or am unsure what alternatives may exist",0],["I am aware that there may be alternatives, but my understanding is limited",1],["I have a clear general understanding that different routes may be available",2]] },
  { id:"q5_2", dimension:"optionsAwareness", prompt:"How carefully have you considered whether the way you are currently thinking of dealing with the dispute actually serves the outcome that matters most to you?", options:[["I have mainly focused on what action to take",0],["I have considered the connection to some extent",1],["I have considered how the route and the outcome I am seeking relate to each other",2]] },
  { id:"q5_3", dimension:"optionsAwareness", prompt:"How clearly have you considered what different ways of dealing with the dispute could mean for cost, time, control, relationships and the ability to continue working or dealing with the other party?", options:[["I have not considered those differences in any depth",0],["I have considered some of them",1],["I have considered the main trade-offs between different approaches",2]] },
  { id:"q5_4", dimension:"optionsAwareness", prompt:"Have you considered which of the paths open to you would be hardest to reverse, whether because of cost, time or the effect on the relationship?", options:[["Not really",0],["To some extent",1],["Yes, I have thought this through",2]] },

  { id:"q6_1", dimension:"preparedness", prompt:"If you had to explain this dispute today to an experienced professional with no prior involvement, how confidently could you give a clear account while also identifying what remains uncertain or contested?", options:[["I would find it difficult to give a clear account without significant explanation or gaps",0],["I could explain the main position, although some areas remain difficult to separate or clarify",1],["I could explain the dispute clearly, including what is established, disputed and still uncertain",2]] },
  { id:"q6_2", dimension:"preparedness", prompt:"How clearly have you identified the assumptions you are currently relying on that, if they proved incorrect, could materially change how you view the dispute?", options:[["I have not really tested my position in that way",0],["I can identify some assumptions, but there may be others I have not considered",1],["I have considered the main assumptions and how a different understanding could affect my position",2]] },
  { id:"q6_3", dimension:"preparedness", prompt:"If you had to make an important decision about this dispute today, how confident are you that you understand enough about the position, information, consequences and uncertainties to make that decision deliberately rather than reactively?", options:[["I would largely be reacting to the immediate situation",0],["I understand several important factors, but some uncertainty would affect my confidence",1],["I could make a considered decision while recognising the uncertainties that remain",2]] },
  { id:"q6_4", dimension:"preparedness", prompt:"If someone experienced challenged the position you currently hold, how prepared would you be to explain not only why you hold it, but what information or development could cause you to reconsider it?", options:[["I have mainly considered why I believe my present position is correct",0],["I could explain my position and recognise some things that might affect it",1],["I could explain my position clearly and identify what could reasonably cause me to reassess it",2]] },
] as const;

export const interpretations = {
  issuePosition: {
    "Needs Attention": { text:"Your responses suggest that the boundaries of the dispute may not yet be fully defined. The issue that first caused concern, the matters now being contested and the outcome being pursued may still overlap. Where that happens, assumptions can begin to carry the same weight as established information and the dispute can become wider without either party necessarily recognising why.", reflection:"If an independent person heard both accounts separately, what would they say the parties actually disagree about?" },
    Developing: { text:"The central disagreement appears identifiable, although some aspects of the wider position remain less settled. You can distinguish several competing issues and perspectives, but there may still be differences between the dispute as you understand it, the other party's account and what can presently be established.", reflection:"Which part of the other party's position would be hardest to dismiss if the matter were considered by someone with no prior involvement?" },
    Established: { text:"Your responses indicate a relatively clear understanding of both the dispute and the competing position surrounding it. That is valuable, but clarity should not be confused with certainty. Disputes can change as information emerges, positions develop or the consequences of a proposed outcome become clearer.", reflection:"What assumption about your current understanding would have the greatest effect on the dispute if it later proved incorrect?" }
  },
  evidenceInformation: {
    "Needs Attention": { text:"The information surrounding the dispute may not yet provide a sufficiently clear picture of how the matter developed. There may be difficulty separating recollection, assumption and information that can presently be established. The challenge is often not the amount of material available, but whether its significance, sequence and limitations are understood.", reflection:"If somebody unfamiliar with the dispute saw only the information presently available, what might they understand differently from you?" },
    Developing: { text:"There appears to be a developing information base, although some aspects of the dispute may remain difficult to establish clearly. There may still be gaps, uncertainty or differences between the available record and the way the dispute is currently understood.", reflection:"Which part of your understanding depends most heavily on information whose meaning the other party might reasonably interpret differently?" },
    Established: { text:"Your responses indicate that the information surrounding the dispute is relatively well understood and capable of being placed in context. A developed information position involves understanding chronology, significance, uncertainty and the distinction between what information shows and what either party says it shows.", reflection:"Which piece of information would be most capable of changing your present understanding if its context or significance proved different from what you currently assume?" }
  },
  exposureStakes: {
    "Needs Attention": { text:"The wider exposure created by the dispute may not yet be fully defined. Attention may currently be concentrated on the immediate disagreement, but the issue attracting the most attention is not always the issue carrying the greatest consequence. Financial exposure can sit alongside time, disruption, relationships, reputation, governance or decisions whose effects continue afterwards.", reflection:"If this dispute were still unresolved six months from now, which consequence would you most regret not having considered earlier?" },
    Developing: { text:"You appear to recognise several wider consequences surrounding the dispute, although their relative importance may not yet be completely settled. There may still be tension between the outcome being pursued and the wider cost or consequence of pursuing it.", reflection:"Has what matters most to you now changed from what mattered most when the dispute began?" },
    Established: { text:"Your responses indicate a relatively developed understanding of what is genuinely at stake beyond the immediate disagreement. You appear to have considered wider consequences and proportionality rather than viewing the dispute solely through the outcome being pursued.", reflection:"Which consequence could most quickly change your present view of what a proportionate outcome looks like?" }
  },
  actionsEscalation: {
    "Needs Attention": { text:"The way the dispute has developed may not yet be fully understood. Attention may remain focused on the original disagreement rather than on how subsequent communications, decisions, delays or formal steps have shaped the present position. Disputes are rarely static.", reflection:"If you compared the dispute today with the dispute at the point it began, what has changed most?" },
    Developing: { text:"You appear to understand much of how the dispute has developed, although the significance of some actions or changes may remain uncertain. A step that appeared minor when it occurred can sometimes become more important as the wider dispute develops.", reflection:"Which communication, decision or period of inactivity would the other party be most likely to say changed the position?" },
    Established: { text:"Your responses indicate a relatively clear understanding of how the dispute has developed and where it currently stands. You appear able to distinguish the original disagreement from subsequent actions and escalation. Understanding what happened is different from determining its legal, procedural or strategic significance.", reflection:"Which development in the history of this dispute would matter most if your present assumptions about its significance proved incorrect?" }
  },
  optionsAwareness: {
    "Needs Attention": { text:"The routes potentially available for dealing with the dispute may not yet have been considered in sufficient context. Attention may be concentrated on taking action rather than on the relationship between the route chosen, the outcome sought and the consequences of pursuing it.", reflection:"Are you currently choosing a route because it best serves what matters to you, or because it is the route you know most about?" },
    Developing: { text:"You appear to recognise that more than one way of dealing with the dispute may exist, although the trade-offs between those approaches may not yet be fully understood. What remains less settled may be how those considerations interact with the outcome you actually want.", reflection:"Which consequence of your preferred approach would be hardest to accept if the dispute did not resolve as you expect?" },
    Established: { text:"Your responses indicate a relatively developed awareness that dispute-management routes involve different consequences and trade-offs. You appear to be considering not simply what can be done, but how different approaches may interact with the outcome sought, the wider relationship and the ability to retain flexibility.", reflection:"What would have to change in this dispute for the route that currently appears most attractive to you to stop making sense?" }
  },
  preparedness: {
    "Needs Attention": { text:"Your responses suggest that you may not yet have brought the different elements of the dispute together sufficiently to make a fully considered decision. This does not mean that your position is weak. Some aspects may still be driven by uncertainty, assumptions or the pressure of the immediate situation.", reflection:"If you had to make an important decision tomorrow, what uncertainty would make you least comfortable doing so?" },
    Developing: { text:"Your responses indicate a developing level of preparedness, with several important aspects of the dispute already understood. There may nevertheless be assumptions or uncertainties that would become more significant if the matter required an important decision or came under greater scrutiny.", reflection:"Which part of your current position would be most difficult to explain confidently if it were challenged by someone with no prior involvement?" },
    Established: { text:"Your responses indicate a relatively developed level of preparedness across the matters explored by the Guide. You appear able to explain the dispute, recognise uncertainty and consider your position beyond the immediate pressure of the disagreement. Strong preparedness includes being willing to test one's own assumptions.", reflection:"What development would most reasonably cause you to reassess the position you currently hold?" }
  }
} as const;

export const complexityFlags = [
  "Have formal proceedings or a formal process already begun?",
  "Is there a known deadline or time-sensitive requirement?",
  "Could the financial, property or business consequences be significant?",
  "Are multiple parties or organisations involved?",
  "Are professional advisers already involved?",
] as const;
